### ISSUE TITLE
Dataset not available

### ISSUE THREAD

**Issue by ankitdwivedi23** [AngusGLChen/LearningQ#1]
The zip downloaded from the links given in the README page contains only the code, not the data.

**Comment by AngusGLChen** [comment]
Hi @ankitdwivedi23 
I have checked the .zip file downloaded from the given links, all of the data are there.

**Comment by ankitdwivedi23** [comment]
Ah, looks like there's some issue with the Windows unzip program. I was able to extract all the data files in ubuntu. Thanks for taking a look! :)

**Comment by daniyelnnr** [comment]
@ankitdwivedi23 Do you still have access to the dataset file? I'm trying to download through the links in the README, but I'm unable to finish it. If you can share this file with me, it would help me a lot.

**Comment by ankitdwivedi23** [comment]
@dnrocha1 Sorry, it was a pretty big dataset, and I deleted it after completing my project :(

**Comment by AngusGLChen** [comment]
Hi All, now you can also download the dataset from [Google Drive](https://drive.google.com/file/d/1D9Qp6BB3prKYSKSM4B__Eo04cw-71JFt/view). Thanks!
