### ISSUE TITLE
About cognitive levels

### ISSUE THREAD

**Issue by WeipingFu** [AngusGLChen/LearningQ#3]
Hello, I wonder if LearningQ includes the labeled data for cognitive levels? And are there specific labeling standards that can be referred to?

**Comment by AngusGLChen** [comment]
Yes, it contains a small set of labelled data according to the Bloom's taxonomy.

**Comment by WeipingFu** [comment]
您的邮件我已收到！

**Comment by WeipingFu** [comment]
Thank u for the reply. I would like to use your data for research, including the labeled data for cognitive levels. Is the labeled data included in the published dataset? I can't seem to find it.

> Yes, it contains a small set of labelled data according to the Bloom's taxonomy.

**Comment by AngusGLChen** [comment]
> Thank u for the reply. I would like to use your data for research, including the labeled data for cognitive levels. Is the labeled data included in the published dataset? I can't seem to find it.
> 
> > Yes, it contains a small set of labelled data according to the Bloom's taxonomy.

[Here](https://drive.google.com/file/d/1DB9P_DP5OMLTPP0P8esCRrEbTJ-X77Ic/view?usp=share_link) are the files of the questions with Bloom's taxonomy labels. Please notice that one question may receive different labels, i.e., the annotators did not reach an agreement.

**Comment by WeipingFu** [comment]
> > Thank u for the reply. I would like to use your data for research, including the labeled data for cognitive levels. Is the labeled data included in the published dataset? I can't seem to find it.
> > > Yes, it contains a small set of labelled data according to the Bloom's taxonomy.
> 
> [Here](https://drive.google.com/file/d/1DB9P_DP5OMLTPP0P8esCRrEbTJ-X77Ic/view?usp=share_link) are the files of the questions with Bloom's taxonomy labels. Please notice that one question may receive different labels, i.e., the annotators did not reach an agreement.
